// Generated by the Webflow Cloud builder. Merge logic lives in ./next.config.webflow.ts.
import userConfig from './clouduser.next.config';
import { withWebflowOverrides } from './next.config.webflow';

// Next.js disallows '/' as basePath, so '/' maps to ''.
const mountPath: string = '/app';
export const webflowBasePath = mountPath === '/' ? '' : mountPath;
export const webflowAssetPrefix = 'https://bf045b65-435b-4504-85fb-e389b4357179.wf-app-prod.cosmic.webflow.services' + webflowBasePath;

export default withWebflowOverrides(userConfig, {
  basePath: webflowBasePath,
  assetPrefix: webflowAssetPrefix,
});
