import type { Metadata } from "next";
import "./globals.css";
import { DevLinkProvider } from "@/webflow/DevLinkProvider";
import { DevLinkFontTags } from "@/webflow/webflow_modules/DevLinkFontTags";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <DevLinkFontTags />
      </head>
      <body className="antialiased">
        <DevLinkProvider>
          {/* Add here any Navbar or Header you want to be present on all pages */}
          {children}
          {/* Add here any Footer you want to be present on all pages */}
        </DevLinkProvider>
      </body>
    </html>
  );
}
